version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/project

jobs:
  run_ui_tests:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run UI tests
          command: |
            set +e
            EXIT_CODE=0
            npm run test:amazonaws
            npm run test:linkedinRegisterationPage
            npm run test:myStore
            set -e
            exit $EXIT_CODE


  run_api_tests:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Api tests
          command: |
            set +e
            EXIT_CODE=0
            npm run dev 8080 &
            SERVER_PID=$!
            sleep 5
            npm run test:api-tests
            CODE=$?
            [ $CODE -ne 0 ] && EXIT_CODE=$CODE
            kill $SERVER_PID
            set -e
            exit $EXIT_CODE

workflows:
  version: 2
  test_pipeline:
    jobs:
      - run_ui_tests
      - run_api_tests:
          requires:
            - run_ui_tests
