jobs:
  run_ui_and_api_tests:
    executor: node_executor
    steps:
      - checkout

      - run:
          name: Install and verify Chrome
          command: |
            sudo apt-get update
            if ! command -v google-chrome &> /dev/null; then
              echo "Installing Chrome..."
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            fi
            google-chrome --version
            which google-chrome

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run UI tests
          command: |
            set +e
            EXIT_CODE=0
            npm run test:amazonaws || EXIT_CODE=$?
            npm run test:linkedinRegisterationPage || EXIT_CODE=$?
            npm run test:myStore || EXIT_CODE=$?
            exit $EXIT_CODE

      - run:
          name: Run API tests (always run, even if UI fails)
          when: always
          command: |
            set +e
            EXIT_CODE=0
            npm run dev 8080 &
            SERVER_PID=$!
            sleep 5
            npm run test:api-tests || EXIT_CODE=$?
            kill $SERVER_PID
            exit $EXIT_CODE
